# Deployment config for Identity Server deployment
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.user]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2IS_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"
[database.user.pool_options]
validationQuery = "SELECT 1"
[realm_manager]
data_source = "WSO2USER_DB"

[database.identity_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2IS_IDENTITY_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"
[database.identity_db.pool_options]
validationQuery="SELECT 1"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2IS_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"
[database.shared_db.pool_options]
validationQuery="SELECT 1"

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

[[datasource]]
id = "WSO2ConsentDS"
url = "jdbc:mysql://mysql:3306/WSO2IS_IDENTITY_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"
"pool_options.validationQuery"="SELECT 1"
"pool_options.maxActive"=50
"pool_options.maxWait" = 60000 # wait in milliseconds
"pool_options.testOnBorrow" = true
"pool_options.jmxEnabled" = false
[authentication.consent]
data_source="jdbc/WSO2ConsentDS"

[cors]
allow_generic_http_requests = true
allow_any_origin = true
allowed_origins = ["http://localhost"]
allow_subdomains = true
supported_methods = [
    "GET",
    "POST",
    "HEAD",
    "OPTIONS"
]
support_any_header = true
supported_headers = []
exposed_headers = []
supports_credentials = true
max_age = 3600
tag_requests = false

[carbon_health_check]
enable= true
[carbon_health_check.health_checker.data_source_health_checker.properties]
'monitored.datasources' = "jdbc/WSO2CarbonDB,jdbc/WSO2UM_DB,jdbc/SHARED_DB"

#SMTP email server configurations
[output_adapter.email]
from_address= "testing@wso2.com"
username= "admin"
password= "admin"
hostname= "mailserver"
port= 1025
enable_start_tls= true
enable_authentication= true


#Enable self registration
[identity_mgt.user_onboarding]
enable_email_verification = true 
lock_on_creation=true
